# Generated by Django 5.1.6 on 2025-07-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Deposite",
            new_name="Deposit",
        ),
        migrations.RenameModel(
            old_name="Widraw",
            new_name="Withdraw",
        ),
    ]
