# Generated by Django 5.1.6 on 2025-07-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_rename_deposite_deposit_rename_widraw_withdraw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdraw",
            name="phone",
            field=models.CharField(max_length=11),
        ),
    ]
